### ISSUE TITLE
Build funktioniert nicht

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [HSchwichtenberg/MiracleListClient#14]
Eine `jquery-fix.map` wird im Repository nicht mitgeliefert, da `.gitignore` das verhindert, `ng build` versucht diese jedoch zu laden.
Diese Datei sollte sich im `Electron`-Verzeichnis befinden (?) obwohl ich die Cordova-App bauen wollte.

**Comment by HSchwichtenberg** [comment]
Diese Datei wird doch automatisch vom dem TypeScript-Compiler aus jquery-fix.ts erstellt. jquery-fix.ts wird für Electron benötigt.
