### ISSUE TITLE
Anmeldung aktuell nicht möglich

### ISSUE THREAD

**Issue by Roemke** [HSchwichtenberg/MiracleListClient#17]
Hallo,
ich bin durch einen ix-Artikel auf das interessante Projekt aufmerksam geworden. 
Ich konnte mich mal auf http://miraclelist.azurewebsites.net/
anmelden, das funktioniert aktuell nicht mehr. OS: Linux, Browser: firefox und chrome. 
Grüße
 Karsten Römke

**Comment by HSchwichtenberg** [comment]
Hallo Herr Römke, bei mir funktioniert es mit mehreren verschiedenen Benutzerkonten. Verwenden Sie eventuell das falsche Kennwort? Leider gibt es bisher keine Funktion, das Kennwort zurückzusetzen. Sie können aber einfach ein neues Konto unter einer andere E-Mail-Adresse anlegen. Das Projekt ist ja nur ein Demo-Projekt. Sie sollten da keine echten Daten ablegen :-)

**Comment by Roemke** [comment]
Hallo,
danke ihnen, das kann natürlich sehr gut
sein, werde ich ausprobieren.

Grüße
Karsten Römke

Mit der Mäuseklaviatur des Smartphones erstellt...

Am 10. Mai 2018 12:02:44 vorm. schrieb dotnetdoktor <notifications@github.com>:
